/**
 * useSlideAnalyzer — NVIDIA Vision slide and document analysis for Pro users
 *
 * Uploads an image to POST /vision/analyze-slide or /vision/analyze-document
 * and returns coaching context generated by Llama 3.2 Vision 11B.
 */
import { useState } from 'react';
import * as ImagePicker from 'expo-image-picker';
import * as FileSystem from 'expo-file-system';
import { useAuthStore } from '../store/authStore';

export interface SlideAnalysisResult {
  slide_summary: string;
  key_vocabulary: string[];
  suggested_phrases: string[];
  coaching_prompt: string;
  practice_questions: string[];
}

export interface DocumentAnalysisResult {
  document_type: string;
  language_score: number;
  strengths: string[];
  improvements: string[];
  rewritten_excerpt: string;
}

export type AnalysisMode = 'slide' | 'document';
export type AnalysisPhase = 'idle' | 'picking' | 'uploading' | 'done' | 'error';

export interface UseSlideAnalyzerReturn {
  phase: AnalysisPhase;
  slideResult: SlideAnalysisResult | null;
  documentResult: DocumentAnalysisResult | null;
  selectedImageUri: string | null;
  error: string | null;
  analyzeSlide: (coachingFocus?: string) => Promise<void>;
  analyzeDocument: () => Promise<void>;
  reset: () => void;
}

const API_BASE = process.env.EXPO_PUBLIC_API_URL ?? 'https://speakflow-api.onrender.com';

export function useSlideAnalyzer(): UseSlideAnalyzerReturn {
  const [phase, setPhase] = useState<AnalysisPhase>('idle');
  const [slideResult, setSlideResult] = useState<SlideAnalysisResult | null>(null);
  const [documentResult, setDocumentResult] = useState<DocumentAnalysisResult | null>(null);
  const [selectedImageUri, setSelectedImageUri] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const { session } = useAuthStore();

  const reset = () => {
    setPhase('idle');
    setSlideResult(null);
    setDocumentResult(null);
    setSelectedImageUri(null);
    setError(null);
  };

  const pickImage = async (): Promise<{ uri: string; mimeType: string } | null> => {
    setPhase('picking');
    try {
      const result = await ImagePicker.launchImageLibraryAsync({
        mediaTypes: ImagePicker.MediaTypeOptions.Images,
        allowsEditing: false,
        quality: 0.85,
      });

      if (result.canceled || !result.assets?.[0]) {
        setPhase('idle');
        return null;
      }

      const asset = result.assets[0];
      setSelectedImageUri(asset.uri);
      const mimeType = asset.mimeType ?? 'image/jpeg';
      return { uri: asset.uri, mimeType };
    } catch {
      setPhase('error');
      setError('Failed to access photo library');
      return null;
    }
  };

  const uploadAndAnalyze = async (
    imageUri: string,
    mimeType: string,
    endpoint: string,
    formData: Record<string, string> = {},
  ): Promise<unknown> => {
    if (!session?.access_token) {
      throw new Error('Not authenticated');
    }

    // Read image as base64 for upload
    const base64 = await FileSystem.readAsStringAsync(imageUri, {
      encoding: FileSystem.EncodingType.Base64,
    });

    // Build multipart form data
    const body = new FormData();

    // Add image as blob-like object (React Native FormData pattern)
    const ext = mimeType.split('/')[1] ?? 'jpg';
    body.append('image', {
      uri: imageUri,
      type: mimeType,
      name: `slide.${ext}`,
    } as unknown as Blob);

    // Add additional form fields
    Object.entries(formData).forEach(([key, value]) => {
      body.append(key, value);
    });

    const response = await fetch(`${API_BASE}${endpoint}`, {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${session.access_token}`,
        // Note: Don't set Content-Type — fetch auto-sets multipart boundary
      },
      body,
    });

    if (response.status === 403) {
      throw new Error('UPGRADE_REQUIRED');
    }

    if (!response.ok) {
      const err = await response.json().catch(() => ({}));
      throw new Error((err as { detail?: string }).detail ?? `HTTP ${response.status}`);
    }

    return response.json();
  };

  const analyzeSlide = async (coachingFocus = 'presentation'): Promise<void> => {
    const image = await pickImage();
    if (!image) return;

    setPhase('uploading');
    setError(null);
    setSlideResult(null);

    try {
      const result = await uploadAndAnalyze(
        image.uri,
        image.mimeType,
        '/vision/analyze-slide',
        { coaching_focus: coachingFocus },
      ) as SlideAnalysisResult;

      setSlideResult(result);
      setPhase('done');
    } catch (err: unknown) {
      const message = err instanceof Error ? err.message : 'Analysis failed';
      setError(message);
      setPhase('error');
    }
  };

  const analyzeDocument = async (): Promise<void> => {
    const image = await pickImage();
    if (!image) return;

    setPhase('uploading');
    setError(null);
    setDocumentResult(null);

    try {
      const result = await uploadAndAnalyze(
        image.uri,
        image.mimeType,
        '/vision/analyze-document',
      ) as DocumentAnalysisResult;

      setDocumentResult(result);
      setPhase('done');
    } catch (err: unknown) {
      const message = err instanceof Error ? err.message : 'Analysis failed';
      setError(message);
      setPhase('error');
    }
  };

  return {
    phase,
    slideResult,
    documentResult,
    selectedImageUri,
    error,
    analyzeSlide,
    analyzeDocument,
    reset,
  };
}
